# Generated by Django 5.2 on 2025-05-03 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('muži', 'Muži'), ('junioři', 'Junioři'), ('dorostenci', 'Dorostenci'), ('ženy', 'Ženy'), ('juniorky', 'Juniorky'), ('dorostenky', 'Dorostenky')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Discipline Name')),
                ('number_of_shots', models.IntegerField(verbose_name='Number of Shots')),
                ('distance', models.IntegerField(verbose_name='Distance (m)')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('rifle', 'Puška'), ('pistol', 'Pistole'), ('shotgun', 'Brokovnice')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=10, unique=True, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('sname', models.CharField(max_length=50, verbose_name='Surname')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shooterdb.club', verbose_name='Club')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.person')),
                ('specialization', models.ManyToManyField(to='shooterdb.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(to='shooterdb.category')),
                ('disciplines', models.ManyToManyField(to='shooterdb.discipline')),
                ('referees', models.ManyToManyField(blank=True, to='shooterdb.referee')),
            ],
        ),
        migrations.CreateModel(
            name='Shooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.person')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.competition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.discipline')),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.shooter')),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun_type', models.CharField(choices=[('rifle', 'Puška'), ('pistol', 'Pistole')], max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('caliber', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.shooter')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.specialization', verbose_name='Specialization'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shooterdb.person')),
                ('specialization', models.ManyToManyField(to='shooterdb.specialization')),
            ],
        ),
    ]
