# Generated by Django 5.2 on 2025-05-03 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shooterdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shooterdb.club'),
            preserve_default=False,
        ),
    ]
